site_name: AI Playtesting
theme:
  name: material
  features:
    # - navigation.tabs
    - navigation.expand
  logo: images/logo.png
  favicon: images/logo.png
  icon:
    repo: fontawesome/brands/github
nav:
  - introduction.md
  - guide.md
  - ai.md
  # - takeaways.md
  - Game Dev along with AI:
    - game/Overview.md
    - Topics:
      - game/Architecture.md
      - game/Unity.md
      - game/Build.md
      - game/DataVisualization.md
      - game/DesktopGUI.md
    - game/Summary.md
  - design.md  
  - Blog:
    - blogs/week1.md
    - blogs/week2.md
    - blogs/week3.md
    - blogs/week4.md
    - blogs/week5.md
    - blogs/week6.md
    - blogs/week7.md
    - blogs/week8.md
    - blogs/week9.md
    - blogs/week10.md
    - blogs/week11.md
    - blogs/week12.md
    - blogs/week13.md
    - blogs/week14.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AIPlaytesting/AIPA


copyright: Copyright &copy; 2020 AI Playtesting

repo_url: https://github.com/AIPlaytesting/AIPA